# Generated by Django 5.2.4 on 2025-07-16 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Currently on duty'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_route_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_distance_today',
            field=models.FloatField(default=0.0, help_text='Distance in kilometers'),
        ),
        migrations.AddField(
            model_name='job',
            name='actual_distance',
            field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='customer_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='estimated_distance',
            field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='route_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='route_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='route_waypoints',
            field=models.JSONField(blank=True, default=list, help_text='Store route coordinates'),
        ),
        migrations.AddField(
            model_name='job',
            name='tracking_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tracking_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.job')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='tracking.driver')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='tracking_dr_driver__0f022f_idx'), models.Index(fields=['current_job', '-timestamp'], name='tracking_dr_current_0edc0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_area', models.CharField(help_text='e.g., PE21, Route 21', max_length=50)),
                ('depot', models.CharField(help_text='e.g., Depot 3', max_length=50)),
                ('planned_stops', models.JSONField(default=list, help_text='List of stop coordinates')),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('estimated_distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('actual_distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('optimized_order', models.JSONField(blank=True, default=list)),
                ('optimization_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tracking.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'status'], name='tracking_ro_driver__8d9581_idx'), models.Index(fields=['route_area'], name='tracking_ro_route_a_f48f6f_idx')],
            },
        ),
    ]
